name: Deploy Azure ARM Template

on:
  workflow_dispatch:
    inputs:
      rssFeedUrl:
        description: "Enter the RSS Feed URL to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: infra/template.json
          parameters: |
              infra/parameters.json
              rssFeedUrl=${{ secrets.RSS_FEED_URL }}
              functionAppUri=${{ secrets.FUNCTION_APP_URI }}
          failOnStdErr: false